### ISSUE TITLE
github站点链接失效？

### ISSUE THREAD

**Issue by s-chance** [j10ccc/my-site#1]
贵站链接[blog.j10ccc.xyz](https://blog.j10ccc.xyz)无法访问？[Social.astro](https://github.com/j10ccc/my-site/blob/main/src/components/Social.astro)

**Comment by j10ccc** [comment]
博客里面的链接还没改过来，github profile 里面的已经更新了。[site.j10ccc.xyz](https://site.j10ccc.xyz)
